import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { initCommand, buildInstallCommands } from "../src/commands/init.js";
import { configCommand, loadConfig } from "../src/commands/config.js";
import { writeFile, mkdtemp, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import type { StackChoices } from "../src/schema.js";

describe("init command", () => {
  it("exposes citty meta with name 'init'", async () => {
    expect(initCommand.meta).toBeDefined();
    const meta = await initCommand.meta;
    expect(meta?.name).toBe("init");
  });

  it("declares the expected args", () => {
    const args = initCommand.args ?? {};
    expect(args).toHaveProperty("name");
    expect(args).toHaveProperty("yes");
    expect(args).toHaveProperty("frontend");
    expect(args).toHaveProperty("backend");
    expect(args).toHaveProperty("db");
    expect(args).toHaveProperty("frontend-host");
    expect(args).toHaveProperty("backend-host");
    expect(args).toHaveProperty("skip-install");
  });
});

describe("buildInstallCommands", () => {
  const stack = (overrides: Partial<StackChoices> = {}): StackChoices => ({
    frontend: "nextjs",
    backend: "hono",
    db: "neon",
    frontendHost: "vercel",
    backendHost: "railway",
    ...overrides,
  });

  it("emits Vercel skills + CLI when frontendHost is vercel", () => {
    const cmds = buildInstallCommands(
      stack({ backendHost: "none" }),
      "/tmp/proj",
    );
    const flat = cmds.map((c) => `${c.cmd} ${c.args.join(" ")}`);

    expect(flat).toEqual([
      "npx -y skills add vercel-labs/next-skills --skill next-best-practices --skill next-cache-components --skill next-upgrade",
      "npx -y skills add vercel/vercel --skill vercel-cli",
      "npx -y skills add vercel-labs/agent-skills --skill vercel-deploy",
      "npx -y skills add vercel-labs/autoship --skill autoship",
      "npm i -g vercel",
    ]);

    // skill installs run in target dir; global npm install does not need a cwd.
    for (const c of cmds) {
      if (c.cmd === "npx") expect(c.cwd).toBe("/tmp/proj");
      if (c.cmd === "npm") expect(c.cwd).toBeUndefined();
    }
  });

  it("emits Railway skills + CLI when backendHost is railway", () => {
    const cmds = buildInstallCommands(
      stack({ frontendHost: "none" }),
      "/tmp/proj",
    );
    const flat = cmds.map((c) => `${c.cmd} ${c.args.join(" ")}`);

    expect(flat).toEqual([
      "npx -y skills add railwayapp/railway-skills",
      "npm i -g @railway/cli",
    ]);
  });

  it("emits Railway skills + CLI when db is railway-postgres", () => {
    const cmds = buildInstallCommands(
      stack({ frontendHost: "none", backendHost: "none", db: "railway-postgres" }),
      "/tmp/proj",
    );
    const flat = cmds.map((c) => `${c.cmd} ${c.args.join(" ")}`);

    expect(flat).toEqual([
      "npx -y skills add railwayapp/railway-skills",
      "npm i -g @railway/cli",
    ]);
  });

  it("does not duplicate Railway commands when both backendHost and db use railway", () => {
    const cmds = buildInstallCommands(
      stack({ frontendHost: "none", backendHost: "railway", db: "railway-postgres" }),
      "/tmp/proj",
    );
    const railwayCmds = cmds.filter((c) => c.description.includes("Railway"));
    expect(railwayCmds).toHaveLength(2); // skills + CLI, not 4
  });

  it("emits both stacks combined", () => {
    const cmds = buildInstallCommands(stack(), "/tmp/proj");
    expect(cmds).toHaveLength(7);
  });

  it("emits nothing when both hosts are 'none' and db is not railway", () => {
    const cmds = buildInstallCommands(
      stack({ frontendHost: "none", backendHost: "none" }),
      "/tmp/proj",
    );
    expect(cmds).toEqual([]);
  });
});

describe("config command", () => {
  it("exposes citty meta with name 'config'", async () => {
    expect(configCommand.meta).toBeDefined();
    const meta = await configCommand.meta;
    expect(meta?.name).toBe("config");
  });

  it("declares the expected args", () => {
    const args = configCommand.args ?? {};
    expect(args).toHaveProperty("frontend");
    expect(args).toHaveProperty("backend");
    expect(args).toHaveProperty("db");
    expect(args).toHaveProperty("frontend-host");
    expect(args).toHaveProperty("backend-host");
  });
});

describe("loadConfig", () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await mkdtemp(join(tmpdir(), "firth-test-"));
  });

  afterEach(async () => {
    await rm(tmpDir, { recursive: true, force: true });
  });

  it("parses a valid firth.config.ts", async () => {
    const configContent = `// firth.config.ts
// Generated by \`firth init\`. Source-of-truth for this project's stack.
// Hand-edit, then run \`firth deploy\` to apply changes.

export default {
  "project": "test-app",
  "stack": {
    "frontend": "nextjs",
    "backend": "hono",
    "db": "railway-postgres",
    "frontendHost": "vercel",
    "backendHost": "railway"
  }
};
`;
    const configPath = join(tmpDir, "firth.config.ts");
    await writeFile(configPath, configContent, "utf8");

    const config = await loadConfig(configPath);
    expect(config.project).toBe("test-app");
    expect(config.stack.db).toBe("railway-postgres");
    expect(config.stack.frontend).toBe("nextjs");
  });

  it("throws on malformed config", async () => {
    const configPath = join(tmpDir, "firth.config.ts");
    await writeFile(configPath, "// empty file\n", "utf8");

    await expect(loadConfig(configPath)).rejects.toThrow(
      "Could not parse firth.config.ts",
    );
  });
});
