/**
 * Schema for firth.config.ts and firth.lock.json.
 *
 * `firth.config.ts` is hand-edited by the user (or their agent) and committed to git.
 * `firth.lock.json` is generated by Firth CLI commands and also committed — it tracks
 * the actual provisioned resources so any agent session can read current infra state.
 *
 * Both files are versioned. Bump `version` and add migration logic when shape changes.
 */

export type FrontendFramework = "nextjs";
export type BackendFramework = "hono" | "express" | "none";
export type DbProvider = "neon" | "railway-postgres" | "none";
export type FrontendHost = "vercel" | "none";
export type BackendHost = "railway" | "none";

export interface StackChoices {
  frontend: FrontendFramework;
  backend: BackendFramework;
  db: DbProvider;
  frontendHost: FrontendHost;
  backendHost: BackendHost;
}

/** Declarative project config. Hand-edited. */
export interface FirthConfig {
  /** Project name (defaults to directory name). */
  project: string;
  /** Stack chosen at init; can be hand-edited later. */
  stack: StackChoices;
}

/** Generated lockfile holding actual provisioned resource state. */
export interface FirthLock {
  version: 1;
  /**
   * Map of provider-keyed resource records.
   * Keys are conventional, e.g. "neon", "vercel", "railway".
   */
  resources: Record<string, ResourceRecord>;
}

export interface ResourceRecord {
  /** Provider-side resource ID (e.g. Neon project id, Vercel project id). */
  id: string;
  /** Optional public URL or endpoint. */
  url?: string;
  /** ISO timestamp of when this resource was first recorded by Firth. */
  createdAt: string;
  /** Provider-specific extra fields are allowed. */
  [k: string]: unknown;
}
